#pragma once

#define MEM_LIMIT_TOTAL_BUDGET (512 * 1024 * 1024)

#define MEM_BLOCK_CONFIG_SIZE (1 * 1024 * 1024)
#define MEM_BLOCK_CONFIG_SLOTS 4

#define MEM_BLOCK_LEVEL_DATA_SIZE (32 * 1024 * 1024)
#define MEM_BLOCK_LEVEL_DATA_SLOTS 16

#define MEM_BLOCK_LEVEL_LOD1_SIZE (16 * 1024 * 1024)
#define MEM_BLOCK_LEVEL_LOD1_SLOTS 32

#define MEM_BLOCK_RENDERER_SIZE (16 * 1024 * 1024)
#define MEM_BLOCK_RENDERER_SLOTS 1

#define MEM_ARENA_MAX_SLOTS 32

#define MEM_ARENA_SLOT_ALIGNMENT (16 * 1024)

#define MEM_POOL_MAIN_SIZE (4 * 1024 * 1024)
#define MEM_POOL_CHUNK_SIZE 256

#define IO_ASYNC_MAX_REQUESTS 64
#define IO_THREAD_SLEEP_USEC 1000
#define IO_DRAIN_MAX_SPINS 10000
#define IO_THREAD_STACK_SIZE (512 * 1024)

#define IO_READ_BUFFER_SIZE (4 * 1024 * 1024)

#define LOG_STRING_MAX_SIZE 512

#define PANIC_UI_PADDING 40

#define MAX_GAME_PAD_PORTS 4

#define INPUT_ANALOG_RAW_CENTER 128
#define INPUT_ANALOG_RAW_SCALE 127.0f
#define INPUT_ANALOG_DEADZONE 0.25f

#define ARCH_MAX_MOUNTED 4
#define RES_MAX_ENTRIES 256

#define SCENE_MAX_RESOURCES 16

#define LEVEL_FARFIELD_MAX_DRAWN 1024
#define LEVEL_SECTOR_HYSTERESIS 0.15f
#define LEVEL_LOD1_FADE_START_CELLS 1.5f
#define LEVEL_LOD1_FADE_WIDTH_CELLS 1.0f
#define LEVEL_LOD1_LOADS_PER_FRAME 2
#define LEVEL_RESIDENT_SECTORS (MEM_BLOCK_LEVEL_DATA_SLOTS - 2)
#define LEVEL_CORE_SLOTS 2
#define LEVEL_SECTOR_SLOT_BASE LEVEL_CORE_SLOTS

#define GFX_SCREEN_WIDTH 1280
#define GFX_SCREEN_HEIGHT 720
#define GFX_SCREEN_REGION_STR "MACOS"

#define GFX_DISPLAY_ASPECT (16.0f / 9.0f)
#define GFX_DISPLAY_ASPECT_X 16
#define GFX_DISPLAY_ASPECT_Y 9

#define PLATFORM_TARGET_FRAME_MICROS 16667

#define GFX_MAX_TEXTURE_WIDTH 4096
#define GFX_MAX_TEXTURE_HEIGHT 4096

#define GFX_TEXTURE_BUDGET_BYTES (256 * 1024 * 1024)

#define GFX_MAX_DRAW_LIST_LENGTH 4096

#define UI_METRIC_SCALE_PERCENT 100

#define UI_MAX_QUADS 16384
#define UI_MAX_FOCUSABLES 256

#define UI_MAX_CLIP_DEPTH 8

#define UI_MAX_STATES 512

#define UI_MAX_OVERLAY_QUADS 2048

#define UI_MAX_FOCUS_GROUPS 8
#define UI_MAX_ID_DEPTH 8

#define UI_MAX_TOASTS 4

#define UI_TEXT_MAX 192

#define UI_TEXT_INPUT_MAX 64

#define GFX_NEAR_PLANE 0.1f
#define GFX_FAR_PLANE 1000.0f

#define GFX_MAX_CAMERAS_3D 4
#define GFX_MAX_LIGHTS 4
#define GFX_SHADOW_MAP_SIZE 1024

#define GFX_MAX_MODEL_MESH_COUNT 32
#define GFX_MAX_CACHED_MODELS 128
