#!/usr/bin/env python3
"""Loading-screen declaration reader and generator.

game/config/loading_screen.json declares the images the built-in loading
screen cycles through while a scene's declared resources are outstanding
(see docs/subsystems/SCENE.md). They must reach C++ running on a console with
no JSON parser, so — like theme.json — the declaration is compiled in rather
than read at runtime.

    python3 tools/loading_screen.py --emit-header build/generated/loading_screen/LoadingScreenAssets.h
"""

import argparse
import json
import os
import sys

DEFAULT_DECLARATION = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "game", "config",
                                   "loading_screen.json")

DEFAULT_CYCLE_SECONDS = 3.0


class LoadingScreenError(ValueError):
    """A declaration that cannot produce a loading screen, with the reason."""


def load(path=DEFAULT_DECLARATION):
    """Read and validate the declaration. Raises LoadingScreenError."""
    where = os.path.basename(path)
    try:
        with open(path, "r", encoding="utf-8-sig") as fh:
            decl = json.load(fh)
    except OSError as e:
        raise LoadingScreenError(f"{where}: cannot be read: {e}")
    except ValueError as e:
        raise LoadingScreenError(f"{where}: is not valid JSON: {e}")

    validate(decl, where)
    return decl


def validate(decl, where):
    images = decl.get("images")
    if not isinstance(images, list) or not images:
        raise LoadingScreenError(f"{where}: declares no images")
    for image in images:
        if not isinstance(image, str) or not image:
            raise LoadingScreenError(f"{where}: every image path must be a non-empty string, got {image!r}")

    cycle = decl.get("cycleSeconds", DEFAULT_CYCLE_SECONDS)
    if not isinstance(cycle, (int, float)) or cycle <= 0:
        raise LoadingScreenError(f"{where}: cycleSeconds must be a positive number, got {cycle!r}")


def _write(path, text):
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


def emit_header(decl, out_path):
    """The images and cycle duration as a header included by exactly one
    engine translation unit (EngineLoadingScreen.cpp)."""
    images = decl["images"]
    cycle = decl.get("cycleSeconds", DEFAULT_CYCLE_SECONDS)

    lines = [
        "#pragma once",
        "",
        "// Generated by tools/loading_screen.py from the title's loading-screen",
        "// declaration. Do not edit: regenerate by building.",
        "",
        "namespace LoadingScreenGenerated",
        "{",
        "    static const char* const kImages[] = {",
    ]
    for image in images:
        lines.append('        "{}",'.format(image.replace("\\", "/")))
    lines += [
        "    };",
        "",
        "    static const int kImageCount = {};".format(len(images)),
        "    static const float kCycleSeconds = {}f;".format(float(cycle)),
        "} // namespace LoadingScreenGenerated",
        "",
    ]
    _write(out_path, "\n".join(lines))
    return out_path


def main(argv=None):
    parser = argparse.ArgumentParser(description="Loading-screen declaration reader and generator")
    parser.add_argument("--declaration", default=DEFAULT_DECLARATION)
    parser.add_argument("--emit-header")
    args = parser.parse_args(argv)

    try:
        decl = load(args.declaration)
    except LoadingScreenError as e:
        print(f"loading_screen: {e}", file=sys.stderr)
        return 1

    if args.emit_header:
        print("loading_screen: wrote", emit_header(decl, args.emit_header))
    else:
        print(f"loading_screen: {len(decl['images'])} image(s) declared, valid")
    return 0


if __name__ == "__main__":
    sys.exit(main())
