#!/usr/bin/env python3
"""nx shader builder.

Both nx renderers draw with one shader source, so a frame that differs between
them is a backend bug rather than a shader difference. The source carries no
version line; this tool prefixes the one each backend needs and emits a C header:

  * dksh - prefixes the version the offline compiler requires, compiles one stage
    with uam and embeds the binary, for the default renderer
  * glsl - prefixes the core-profile version and embeds the text, which the
    reference renderer's driver compiles at run time

See docs/nx/renderers/DEKO3D.md and docs/nx/renderers/OPENGL.md.

Usage:
    python3 tools/nx_shader.py dksh --stage vert --input scene.vert.glsl \\
        --output build/generated/nx/scene_vert_dksh.h --symbol g_SceneVertexDksh
    python3 tools/nx_shader.py glsl --input scene.vert.glsl \\
        --output build/generated/nx/scene_vert_glsl.h --symbol g_SceneVertexGlsl
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import compile_shader

DKSH_VERSION = "#version 460"
GLSL_VERSION = "#version 430 core"
DKSH_MAGIC = b"DKSH"
STAGES = ("vert", "tess_ctrl", "tess_eval", "geom", "frag", "comp")


class NxShaderError(Exception):
    """A shader this build refuses to embed."""


def versioned_source(input_path, version):
    """@return The shader source with the version line prefixed.
    @raise NxShaderError When the source already declares a version."""
    with open(input_path, encoding="utf-8") as handle:
        body = handle.read()
    for line in body.splitlines():
        if line.strip().startswith("#version"):
            raise NxShaderError("{} declares its own version; the shared source must not".format(input_path))
    return "{}\n{}".format(version, body)


def find_uam(explicit):
    """Explicit path, then $DEVKITPRO/tools/bin, then PATH."""
    candidates = [explicit]
    devkitpro = os.environ.get("DEVKITPRO")
    if devkitpro:
        candidates.append(os.path.join(devkitpro, "tools", "bin", "uam"))
    candidates.append(shutil.which("uam"))
    for candidate in candidates:
        if candidate and os.path.exists(candidate):
            return candidate
    raise NxShaderError("uam not found; install switch-dev (see docs/nx/BUILD.md) or pass --uam")


def compile_dksh(uam, stage, input_path):
    """Compile one stage and return the binary."""
    if stage not in STAGES:
        raise NxShaderError("unknown stage '{}', expected one of {}".format(stage, ", ".join(STAGES)))

    source = versioned_source(input_path, DKSH_VERSION)
    with tempfile.TemporaryDirectory() as scratch:
        glsl = os.path.join(scratch, os.path.basename(input_path))
        dksh = os.path.join(scratch, "out.dksh")
        with open(glsl, "w", encoding="utf-8", newline="\n") as handle:
            handle.write(source)

        proc = subprocess.run([uam, "-o", dksh, "-s", stage, glsl], capture_output=True, text=True)
        output = ((proc.stdout or "") + (proc.stderr or "")).strip()
        if proc.returncode != 0 or not os.path.exists(dksh):
            raise NxShaderError("compiling {} failed:\n{}".format(input_path, output or "(no output)"))

        with open(dksh, "rb") as handle:
            blob = handle.read()

    if blob[:4] != DKSH_MAGIC:
        raise NxShaderError("{} did not compile to a shader binary (magic {!r})".format(input_path, blob[:4]))
    return blob


def c_string_literal(text):
    """@return The text as a sequence of C string literal lines."""
    lines = []
    for line in text.splitlines():
        escaped = line.replace("\\", "\\\\").replace('"', '\\"')
        lines.append('    "{}\\n"'.format(escaped))
    return lines


def write_glsl_header(source, symbol, out_path, source_name):
    lines = [
        "#pragma once",
        "",
        "// Generated by tools/nx_shader.py from {}.".format(source_name),
        "// Do not edit: regenerate by building.",
        "",
        "static const char {}[] =".format(symbol),
    ]
    lines += c_string_literal(source)
    lines += ["    ;", ""]

    os.makedirs(os.path.dirname(os.path.abspath(out_path)) or ".", exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))


def main(argv=None):
    parser = argparse.ArgumentParser(description="Build an nx shader header")
    parser.add_argument("mode", choices=("dksh", "glsl"))
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--symbol", required=True)
    parser.add_argument("--stage", help="dksh only: the pipeline stage")
    parser.add_argument("--uam", help="dksh only: path to the offline compiler")
    args = parser.parse_args(argv)

    try:
        name = os.path.basename(args.input)
        if args.mode == "dksh":
            if not args.stage:
                raise NxShaderError("dksh mode needs --stage")
            blob = compile_dksh(find_uam(args.uam), args.stage, args.input)
            compile_shader.write_header(blob, args.symbol, args.output, name)
            with open(args.output, encoding="utf-8") as handle:
                header = handle.read()
            with open(args.output, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(header.replace("tools/compile_shader.py", "tools/nx_shader.py", 1))
            print("nx_shader: {} -> {} ({} bytes)".format(name, args.output, len(blob)))
        else:
            source = versioned_source(args.input, GLSL_VERSION)
            write_glsl_header(source, args.symbol, args.output, name)
            print("nx_shader: {} -> {}".format(name, args.output))
    except (NxShaderError, OSError) as error:
        sys.stderr.write("nx_shader: {}\n".format(error))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
